hash-format = "sha256"

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/mclogs.pw.toml"
hash = "5417107980642ac94c2ec399132939ab4a87d83eff48d4fb7aada6f662b177b7"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "58ceb046380be656ff449cd62b79bc9540ff08b8502e1e8291c9715e5ca3c829"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "4735b502110228fe33b9a957794689f309e3a7019fff26390a10f750d074ed32"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "2c1661e65d47c2942d2c3e926698d0762672224f1925c7f25105b964ce25b093"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true
