name = "Modpack"
author = "Seb"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be2e48b5d3b85a28c1f998a0681b8765db938af9dd100f9b1993875364759a9f"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.50-beta"
